export const COUNTRIES_API_BASE_URL = process.env.REACT_APP_COUNTRY_API
export const WEATHER_API_BASE_URL = process.env.REACT_APP_WEATHER_API
export const WEATHER_API_ACCESS_KEY = process.env.REACT_APP_WEATHER_API_KEY
